apiVersion: security.fizsar.github.io/v1alpha1
kind: CryptoAudit
metadata:
  labels:
    app.kubernetes.io/name: quantum-ready-operator
    app.kubernetes.io/managed-by: kustomize
  name: cryptoaudit-sample
spec:
  # TODO(user): Add fields here
