//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoAudit) DeepCopyInto(out *CryptoAudit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoAudit.
func (in *CryptoAudit) DeepCopy() *CryptoAudit {
	if in == nil {
		return nil
	}
	out := new(CryptoAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CryptoAudit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoAuditList) DeepCopyInto(out *CryptoAuditList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CryptoAudit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoAuditList.
func (in *CryptoAuditList) DeepCopy() *CryptoAuditList {
	if in == nil {
		return nil
	}
	out := new(CryptoAuditList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CryptoAuditList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoAuditSpec) DeepCopyInto(out *CryptoAuditSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoAuditSpec.
func (in *CryptoAuditSpec) DeepCopy() *CryptoAuditSpec {
	if in == nil {
		return nil
	}
	out := new(CryptoAuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoAuditStatus) DeepCopyInto(out *CryptoAuditStatus) {
	*out = *in
	if in.Hallazgos != nil {
		in, out := &in.Hallazgos, &out.Hallazgos
		*out = make([]Hallazgo, len(*in))
		copy(*out, *in)
	}
	in.UltimaAuditoria.DeepCopyInto(&out.UltimaAuditoria)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoAuditStatus.
func (in *CryptoAuditStatus) DeepCopy() *CryptoAuditStatus {
	if in == nil {
		return nil
	}
	out := new(CryptoAuditStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hallazgo) DeepCopyInto(out *Hallazgo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hallazgo.
func (in *Hallazgo) DeepCopy() *Hallazgo {
	if in == nil {
		return nil
	}
	out := new(Hallazgo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferenciaSecret) DeepCopyInto(out *ReferenciaSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferenciaSecret.
func (in *ReferenciaSecret) DeepCopy() *ReferenciaSecret {
	if in == nil {
		return nil
	}
	out := new(ReferenciaSecret)
	in.DeepCopyInto(out)
	return out
}
